import Phaser from 'phaser';
import {loadAuthored,lineOfSight,ZONES,type DungeonDefinition,type DungeonObject} from './dungeon';
import './style.css';
import '@fontsource/cinzel/latin-500.css';
import '@fontsource/cinzel/latin-600.css';
import '@fontsource/manrope/latin-400.css';
import '@fontsource/manrope/latin-700.css';
import {generateDungeon} from './generator';

const ui=document.querySelector<HTMLDivElement>('#ui')!;
const asset=(path:string)=>`${import.meta.env.BASE_URL}${path.replace(/^\/+/,"")}`;
type Settings={sound:boolean;reducedFlash:boolean;brightness:number};
const settings:Settings={sound:true,reducedFlash:false,brightness:1};
let best=0,completed=false;
try{const s=JSON.parse(localStorage.getItem('cryptward-save-v1')||'{}');Object.assign(settings,s.settings||{});settings.brightness=Math.max(.85,Math.min(1.4,Number(settings.brightness)||1));best=Number(s.best)||0;completed=!!s.completed;}catch{}
function save(){if(new URLSearchParams(location.search).has('verify'))return;try{localStorage.setItem('cryptward-save-v1',JSON.stringify({schemaVersion:1,settings,best,completed}));}catch{}}
let audio:AudioContext|undefined;
function sound(freq=250,duration=.1,type:OscillatorType='triangle',volume=.04){if(!settings.sound)return;try{audio??=new AudioContext();void audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.35),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
const stats:Record<string,{hp:number;speed:number;damage:number;score:number;size:number}>={ash_rat:{hp:20,speed:79,damage:6,score:50,size:39},bonebound:{hp:42,speed:43,damage:12,score:90,size:59},cinder_acolyte:{hp:34,speed:47,damage:10,score:120,size:59},furnace_brute:{hp:120,speed:31,damage:20,score:250,size:78},ember_nest:{hp:95,speed:0,damage:0,score:400,size:78},bellows_warden:{hp:750,speed:25,damage:17,score:2500,size:130}};
const xpRewards:Record<string,number>={ash_rat:10,bonebound:18,cinder_acolyte:24,furnace_brute:45,ember_nest:55,bellows_warden:0};
type Entity={id:number;family:string;x:number;y:number;hp:number;max:number;next:number;born:number;hit:number;sprite:Phaser.GameObjects.Image;shadow:Phaser.GameObjects.Ellipse;home?:DungeonObject;tell?:{until:number;x:number;y:number;radius:number};dead?:boolean};
type Obj=DungeonObject&{done?:boolean;sprite?:Phaser.GameObjects.Image;next?:number};
type Shot={x:number;y:number;vx:number;vy:number;life:number;damage:number};
type Spark={x:number;y:number;vx:number;vy:number;life:number;max:number;color:number;size:number};
let scene:GameScene;
class GameScene extends Phaser.Scene {
 d!:DungeonDefinition;objects:Obj[]=[];enemies:Entity[]=[];shots:Shot[]=[];sparks:Spark[]=[];hero!:Phaser.GameObjects.Image;shadow!:Phaser.GameObjects.Ellipse;fx!:Phaser.GameObjects.Graphics;light!:Phaser.GameObjects.Graphics;world!:Phaser.GameObjects.Image;
 x=176;y=784;hp=100;maxHp=100;level=1;xp=0;bladeDamage=14;burstDamage=30;ember=100;score=0;shards=0;keys=0;nests=0;deaths=0;secrets=0;elapsed=0;clock=0;attackAt=0;dashAt=0;dashUntil=0;invuln=0;guard=0;burstAt=0;face=0;id=0;step=0;lastHud=0;zone=1;visited=new Set<number>([1]);active=false;paused=false;menu=true;mapOpen=false;bossDead=false;gateOpen=false;furnaceOpen=false;checkpoint={x:240,y:720};toastUntil=0;attackAnim=0;move=false;titleTime=0;keysDown=new Set<string>();mouseAim=false;pointer={x:0,y:0};touch?:{x:number;y:number;time:number;dx:number;dy:number};zoom=1.6;flow=new Int16Array(0);flowAt=0;decor:Phaser.GameObjects.Image[]=[];explored=new Uint8Array(0);mapRevealAt=0;
 constructor(){super('Cryptward');scene=this;}
 preload(){document.documentElement.style.setProperty('--cover-image',`url("${asset('assets/cryptward-cover.png')}")`);ui.innerHTML='<div class="loading"><div class="eyebrow">Opening the iron gates</div><h2>CRYPTWARD</h2><p id="load">PREPARING THE ASHVAULT</p></div>';this.load.json('map',asset('levels/level-01-ashvault.json'));this.load.json('catalog',asset('templates/ashvault-room-catalog.json'));this.load.image('tiles',asset('assets/atlases/dungeon_tiles_hd_8x8_128.png'));
  for(const n of ['idle_south','idle_north','idle_east','idle_west','idle_breathe_01','idle_breathe_02','idle_breathe_03','idle_breathe_04','walk_alt_01','walk_alt_02','walk_alt_03','walk_alt_04','attack_01','attack_02','attack_03','attack_04','cast_ember','dash','hit','defeat'])this.load.image('hero_'+n,asset('assets/frames/hero/'+n+'.png'));
  for(const f of Object.keys(stats))for(const a of ['idle','move_01','move_02','attack','hit','defeat'])this.load.image(f+'_'+a,asset(`assets/frames/enemies/${f}_${a}.png`));
  for(const n of ['health_tonic_small','health_tonic_large','brass_key','coin_pile','teal_mana_shard','ember_charge','shield_charm','score_relic','chest_closed','chest_open','lever_off','lever_on','checkpoint_brazier','bone_pile_prop','hanging_chain','weapon_rack','warning_banner','small_forge'])this.load.image(n,asset('assets/frames/items_ui/'+n+'.png'));
  for(const n of ['gate_locked','door_open_arch','boss_seal','column_teal','brazier_column','secret_ember_crack','bridge_chain','ashvault_bridge'])this.load.image(n,asset('assets/frames/dungeon/'+n+'.png'));
  for(let n=1;n<=8;n++)this.load.image('portal_'+n,asset('assets/frames/effects/portal_0'+n+'.png'));
  this.load.on('progress',(v:number)=>{const l=document.querySelector('#load');if(l)l.textContent=`KINDLING THE FLAME · ${Math.round(v*100)}%`;});
 }
 create(){this.d=loadAuthored(this.cache.json.get('map'));this.makeMap();this.fx=this.add.graphics().setDepth(10000);this.light=this.add.graphics().setDepth(9000).setBlendMode(Phaser.BlendModes.ADD);this.setupInput();this.reset();this.showTitle();this.scale.on('resize',()=>this.resize());document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.active&&!this.paused)this.pause();});window.addEventListener('blur',()=>{this.keysDown.clear();if(this.active&&!this.paused)this.pause();});this.resize();document.querySelector<HTMLCanvasElement>('#game canvas')!.style.filter=`brightness(${settings.brightness})`;}
 resize(){this.zoom=this.scale.width<750?1.35:Math.max(1.45,Math.min(2.05,this.scale.width/800));this.cameras.main.setZoom(this.zoom);}
 makeMap(){this.world?.destroy();for(const o of this.decor)o.destroy();this.decor=[];if(this.textures.exists('floor'))this.textures.remove('floor');const w=this.d.width*32,h=this.d.height*32;const tex=this.textures.createCanvas('floor',w,h)!;const c=tex.context,atlas=this.textures.get('tiles').getSourceImage() as HTMLImageElement;
  c.fillStyle='#081319';c.fillRect(0,0,w,h);
  const wall=(x:number,y:number)=>x<0||y<0||x>=this.d.width||y>=this.d.height||this.d.collision[y*this.d.width+x]>0;
  // The playable dungeon remains a square grid, but its paint treatment creates a
  // readable three-quarter illusion: high northern walls, deep southern faces, and
  // recessed gaps. This keeps collision and controls completely unchanged.
  const bridge=this.d.objects.find(o=>o.name==='bridge_01');
  const bridgeTile=(x:number,y:number)=>!!bridge&&x>=Math.floor(bridge.x/32)-1&&x<=Math.floor(bridge.x/32)+1&&y>=Math.floor(bridge.y/32)-4&&y<=Math.floor(bridge.y/32)+4;
  for(let y=0;y<this.d.height;y++)for(let x=0;x<this.d.width;x++){const i=y*this.d.width+x,px=x*32,py=y*32,isWall=wall(x,y),n=((x*73856093)^(y*19349663))>>>0;
   if(bridgeTile(x,y)){
    const glow=c.createLinearGradient(px,py,px,py+32);glow.addColorStop(0,'#071d25');glow.addColorStop(.5,'#02080d');glow.addColorStop(1,'#0b2d35');c.fillStyle=glow;c.fillRect(px,py,32,32);
    c.fillStyle='#2f9b9d24';c.fillRect(px,py+6,32,3);c.fillRect(px,py+24,32,2);c.strokeStyle='#69d7c135';c.beginPath();c.moveTo(px+4,py+2);c.lineTo(px+25,py+30);c.moveTo(px+28,py+4);c.lineTo(px+10,py+31);c.stroke();
   }else if(!isWall){
    const floor=c.createLinearGradient(px,py,px,py+32);const shade=['#667672','#707d75','#62736f','#5b6c69'][n%4];floor.addColorStop(0,'#89918a');floor.addColorStop(.2,shade);floor.addColorStop(1,'#3c504f');c.fillStyle=floor;c.fillRect(px,py,32,32);
    c.globalAlpha=.28;const floorTile=[0,1,2,6][n%4];c.drawImage(atlas,(floorTile%8)*128+30,Math.floor(floorTile/8)*128+36,72,68,px,py,32,32);c.globalAlpha=1;
    c.strokeStyle='#d6d1b84a';c.strokeRect(px+.5,py+.5,31,31);c.fillStyle='#06151a65';c.fillRect(px,py+29,32,3);
    if(n%7===0){c.strokeStyle='#112a303d';c.beginPath();c.moveTo(px+4,py+3);c.lineTo(px+13,py+14);c.lineTo(px+8,py+24);c.stroke();}
    if(wall(x,y-1)){c.fillStyle='#071217a8';c.fillRect(px,py,32,11);c.fillStyle='#c3aa70a8';c.fillRect(px,py,32,2);c.fillStyle='#816c43aa';c.fillRect(px,py+3,32,2);}
    if(wall(x-1,y)){c.fillStyle='#06121848';c.fillRect(px,py,6,32);}
   }else{
    const stone=['#1b2b32','#1e3038','#26353b'][n%3];c.fillStyle=stone;c.fillRect(px,py,32,32);c.fillStyle='#0a151b';c.fillRect(px,py+15,32,17);c.strokeStyle='#09161b';c.strokeRect(px+.5,py+.5,31,15);c.strokeRect(px-15.5,py+16.5,31,15);c.strokeStyle='#66727666';c.beginPath();c.moveTo(px+1,py+1);c.lineTo(px+31,py+1);c.stroke();
    if(!wall(x,y+1)){c.fillStyle='#050d12';c.fillRect(px,py+18,32,14);c.fillStyle='#c7ad70';c.fillRect(px,py+3,32,3);c.fillStyle='#715936';c.fillRect(px,py+6,32,4);c.fillStyle='#a1926f';c.fillRect(px,py+10,32,2);}
    if(!wall(x+1,y)){c.fillStyle='#c1ab71';c.fillRect(px+28,py,4,32);}if(!wall(x-1,y)){c.fillStyle='#897344';c.fillRect(px,py,4,32);}if(!wall(x,y-1)){c.fillStyle='#d0b87b';c.fillRect(px,py,32,3);}
   }
  }

  // Inlaid ward medallions give chambers an identity without obscuring the floor.
  for(let z=1;z<=8;z++){const cells=this.d.zones.map((v,i)=>v===z&&!this.d.collision[i]?i:-1).filter(i=>i>=0);if(!cells.length)continue;const cx=cells.reduce((sum,i)=>sum+i%this.d.width,0)/cells.length*32+16,cy=cells.reduce((sum,i)=>sum+Math.floor(i/this.d.width),0)/cells.length*32+16;if(wall(Math.floor(cx/32),Math.floor(cy/32)))continue;c.save();c.beginPath();for(const i of cells)c.rect(i%this.d.width*32,Math.floor(i/this.d.width)*32,32,32);c.clip();c.translate(cx,cy);c.strokeStyle=z===8?'#b191585e':'#d5c18b38';c.lineWidth=2;const r=z===1?67:z===8?105:83;for(const radius of [r,r-7,r*.47]){c.beginPath();c.arc(0,0,radius,0,Math.PI*2);c.stroke();}for(let k=0;k<12;k++){c.save();c.rotate(k*Math.PI/6);c.fillStyle='#d8c59366';c.fillRect(-1,-r+12,2,7);c.restore();}c.beginPath();c.moveTo(0,-r*.4);c.lineTo(r*.28,0);c.lineTo(0,r*.4);c.lineTo(-r*.28,0);c.closePath();c.stroke();c.restore();}
  tex.refresh();this.world=this.add.image(0,0,'floor').setOrigin(0).setDepth(-100);this.cameras.main.setBackgroundColor('#050d12');
  // Boundary sconces and readable raised props; decoration never changes collision.
  for(let y=1;y<this.d.height-1;y++)for(let x=1;x<this.d.width-1;x++){if(wall(x,y)&&[[x-1,y],[x+1,y],[x,y-1],[x,y+1]].filter(([a,b])=>!wall(a,b)).length>=3){this.decor.push(this.add.image(x*32+16,y*32+25,'column_teal').setDisplaySize(43,61).setOrigin(.5,.8).setDepth(y*32+25));}if(wall(x,y)&&!wall(x,y+1)&&x%4===0){this.decor.push(this.add.image(x*32+16,y*32+24,'brazier_column').setDisplaySize(31,42).setDepth(y*32+24));}}
 }
 reset(){for(const e of this.enemies){e.sprite.destroy();e.shadow.destroy();}for(const o of this.objects)o.sprite?.destroy();this.enemies=[];this.shots=[];this.sparks=[];this.hero?.destroy();this.shadow?.destroy();this.objects=structuredClone(this.d.objects);this.x=176;this.y=784;const spawn=this.objects.find(o=>o.type==='spawn')!;this.x=spawn.x;this.y=spawn.y;this.maxHp=100;this.hp=this.maxHp;this.level=1;this.xp=0;this.bladeDamage=14;this.burstDamage=30;this.ember=100;this.score=0;this.shards=0;this.keys=0;this.nests=0;this.deaths=0;this.secrets=0;this.elapsed=0;this.clock=0;this.attackAt=0;this.dashAt=0;this.dashUntil=0;this.burstAt=0;this.invuln=0;this.bossDead=false;this.gateOpen=false;this.furnaceOpen=false;this.zone=1;this.visited=new Set([1]);this.explored=new Uint8Array(this.d.width*this.d.height);this.mapRevealAt=0;this.revealMap(this.x,this.y);const cp=this.objects.find(o=>o.type==='checkpoint')!;this.checkpoint={x:cp.x,y:cp.y};
  for(const o of this.objects){if(o.name==='door_rat_run')o.done=true;let texture='';switch(o.type){case 'pickup':texture=o.properties.item==='seal_shard'?'teal_mana_shard':o.properties.item;break;case 'checkpoint':texture='checkpoint_brazier';break;case 'door':texture=o.done?'door_open_arch':'gate_locked';break;case 'secret':texture='secret_ember_crack';break;case 'chest':texture='chest_closed';break;case 'lever':texture='lever_off';break;case 'bridge':texture='ashvault_bridge';break;case 'exit':texture='portal_1';break;case 'spawner':this.spawn('ember_nest',o.x,o.y,o);break;case 'boss':this.spawn('bellows_warden',o.x,o.y,o);break;}
   if(texture){const bridge=o.type==='bridge';o.sprite=this.add.image(o.x,o.y,texture).setDepth(bridge?o.y+20:o.y).setDisplaySize(bridge?154:o.type==='door'?43:o.type==='exit'?96:45,bridge?288:o.type==='door'?64:o.type==='exit'?96:45);if(bridge)o.sprite.setOrigin(.5,.5).setAlpha(.96);if(o.type==='exit')o.sprite.setAlpha(.25);}
  }
  this.shadow=this.add.ellipse(this.x,this.y+9,30,13,0x031015,.55);this.hero=this.add.image(this.x,this.y,'hero_idle_south').setDisplaySize(57,57).setOrigin(.5,.75);this.cameras.main.centerOn(this.x,this.y);this.keysDown.clear();this.step=0;this.lastHud=0;this.flowAt=0;this.mouseAim=false;this.face=0;this.touch=undefined;
 }
 setupInput(){window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();this.keysDown.add(e.code);if(e.repeat)return;if(e.code==='KeyF'){if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>{});}if(e.code==='Escape'){if(this.active)this.paused?this.resume():this.pause();}if(e.code==='KeyM'&&this.active){if(this.mapOpen)this.resume();else this.showMap();}if(!this.active||this.paused)return;if(e.code==='Space')this.burst();if(e.code==='ShiftLeft'||e.code==='ShiftRight')this.dash();if(e.code==='KeyE')this.interact();});window.addEventListener('keyup',e=>this.keysDown.delete(e.code));
  this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{if(p.wasTouch&&this.touch){this.touch.dx=p.x-this.touch.x;this.touch.dy=p.y-this.touch.y;}else{this.pointer={x:p.x,y:p.y};this.mouseAim=true;}});
  this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(!this.active||this.paused)return;if(p.wasTouch)this.touch={x:p.x,y:p.y,time:performance.now(),dx:0,dy:0};else if(p.rightButtonDown())this.burst();else this.attack();});this.input.on('pointerup',(p:Phaser.Input.Pointer)=>{if(!p.wasTouch||!this.touch)return;const t=this.touch,dt=performance.now()-t.time,dist=Math.hypot(t.dx,t.dy);if(dt<180&&dist<12)this.burst();else if(dt>=350&&dist<12)this.interact();else if(dt<360&&dist/dt*1000>850){this.face=Math.atan2(t.dy,t.dx);this.dash();}this.touch=undefined;});this.input.mouse?.disableContextMenu();
 }
 showTitle(){this.active=false;this.menu=true;this.paused=false;ui.innerHTML=`<div class="overlay"><div class="topline"><span class="eyebrow">A descent into the forgotten</span><span class="status-dot">◆ &nbsp; PC EDITION</span></div><div class="title-content"><div class="wordmark"><div class="sigil"><span>†</span></div><span class="eyebrow">KEEP THE FLAME ALIVE</span></div><h1>CRYPTWARD</h1><div class="subtitle">THE ASHVAULT</div><div class="rule"></div><p class="intro">Beneath the stone, the furnaces still breathe.<br>Break their chains. Reclaim the three seals.<br>Leave before your last ember fades.</p><div style="height:22px"></div><button id="start" class="primary">ENTER THE ASHVAULT <span>→</span></button><button id="expedition" class="secondary" ${completed?'':'disabled'}>${completed?'EXPEDITION':'EXPEDITION · COMPLETE CAMPAIGN'} <span>${completed?'→':'◇'}</span></button><button id="settings" class="secondary">SETTINGS <span>⚙</span></button><div style="font-size:9px;letter-spacing:1.6px;color:#7e9188;margin-top:21px">WASD TO MOVE &nbsp; · &nbsp; MOUSE TO AIM &nbsp; · &nbsp; AUTO-ATTACK</div></div><div class="title-bottom"><span>CHAPTER I / THE ASHVAULT</span><span>SOLO DUNGEON CRAWLER</span></div><div class="title-right"><span class="eyebrow">YOUR WARDEN AWAITS</span><strong>One flame. One way out.</strong><span class="muted" style="font-size:10px">${best?'BEST RUN · '+best.toLocaleString():'An original dark-fantasy adventure'}</span></div></div>`;document.querySelector('#start')!.addEventListener('click',()=>this.start());document.querySelector('#settings')!.addEventListener('click',()=>this.showSettings(true));document.querySelector('#expedition')!.addEventListener('click',()=>this.showExpedition());}
 start(expedition=false,seed=Date.now()|0){sound(170,.4,'sine');this.d=expedition?generateDungeon(seed,this.cache.json.get('catalog')):loadAuthored(this.cache.json.get('map'));this.makeMap();this.reset();this.active=true;this.menu=false;this.paused=false;this.renderHud();this.toast('The Ashvault opens. Keep your flame alive.');}
 showExpedition(){ui.insertAdjacentHTML('beforeend',`<div class="modal-shade"><div class="modal"><div class="eyebrow">BEYOND THE FIRST DESCENT</div><h2>Expedition</h2><p>Ten chambers. Familiar dangers. A new arrangement of the Ashvault. Replay a seed to return to the same floor.</p><label class="setting">Floor seed <input id="seed" type="number" min="-2147483648" max="2147483647" value="${Date.now()|0}" style="width:160px;padding:10px;background:#0c191f;color:#dcc596;border:1px solid #655e43"></label><p id="seed-error"></p><button class="primary" id="launch-expedition">BEGIN EXPEDITION <span>→</span></button><button class="secondary" id="cancel-expedition">BACK <span>↩</span></button></div></div>`);document.querySelector('#launch-expedition')!.addEventListener('click',()=>{const raw=(document.querySelector('#seed') as HTMLInputElement).value,seed=Number(raw);if(!raw||!Number.isInteger(seed)||seed<-2147483648||seed>2147483647){document.querySelector('#seed-error')!.textContent='Enter a whole number from −2147483648 to 2147483647.';return;}this.start(true,seed);});document.querySelector('#cancel-expedition')!.addEventListener('click',()=>this.showTitle());}
 renderHud(){ui.innerHTML=`<div class="hud"><div class="hud-top"><div class="vitals"><div class="portrait"><img src="/assets/frames/hero/idle_south.png" alt="Ash Warden"></div><div class="meters"><div class="meter-label"><span>VITALITY</span><span id="health-value">100 / 100</span></div><div class="meter"><i id="health-bar"></i></div><div class="meter-label"><span>EMBER</span><span id="ember-value">100 / 100</span></div><div class="meter ember"><i id="ember-bar"></i></div><div class="meter-label xp-label"><span id="level-value">WARDEN · LEVEL 1</span><span id="xp-value">0 / 120 XP</span></div><div class="meter xp"><i id="xp-bar"></i></div></div></div><div class="score"><span class="eyebrow">ASHVAULT SCORE</span><strong id="score">000000</strong></div><div class="top-right"><div><div class="eyebrow" style="margin-bottom:12px;font-size:8px">SEAL SHARDS</div><div class="shards" id="shards"></div></div><span id="key" style="color:#a4b39c;font-size:12px">⚿ 0</span><button id="pause" class="small-button" aria-label="Pause game">Ⅱ &nbsp; ESC</button></div></div><div class="objective"><span class="eyebrow">THE DESCENT</span><h3 id="objective-title"></h3><p id="objective-copy"></p><div class="progress" id="nest-count"></div></div><div class="map-panel"><div class="eyebrow" style="font-size:8px">THE ASHVAULT</div><canvas id="minimap" width="256" height="192"></canvas><div class="map-caption"><span id="explored">EXPLORED 12%</span><span>M · MAP</span></div></div><div class="boss hidden" id="boss"><h3>THE BELLOWS WARDEN</h3><div class="meter"><i id="boss-bar"></i></div><div class="phase" id="phase"></div></div><div class="bottom"><div class="location"><span class="eyebrow" style="font-size:8px">CHAPTER I &nbsp; / &nbsp; <span id="time">00:00</span></span><h3 id="zone">Ember Vestibule</h3><p>BELOW THE FORGOTTEN CITY</p></div><div class="abilities"><div class="ability"><span class="keycap">AUTO</span><div class="icon">⚔</div><div class="name">WARD BLADE</div></div><div class="ability" id="burst-slot"><span class="keycap">SPACE</span><div class="icon">♨</div><div class="name">EMBER BURST</div></div><div class="ability" id="dash-slot"><span class="keycap">SHIFT</span><div class="icon">➶</div><div class="name">ASH STEP</div></div></div><div class="control-hint">W A S D &nbsp; MOVE &nbsp; · &nbsp; MOUSE AIM<br>E &nbsp; INTERACT &nbsp; · &nbsp; M &nbsp; MAP &nbsp; · &nbsp; F &nbsp; FULLSCREEN</div></div><div class="toast hidden" id="toast"></div><div class="interact hidden" id="interact"></div><div class="touch"><button id="touch-e" aria-label="Interact">E</button></div></div>`;document.querySelector('#pause')!.addEventListener('click',()=>this.pause());document.querySelector('#touch-e')!.addEventListener('click',()=>this.interact());this.updateHud();}
 objective(){if(!this.objects.find(o=>o.name==='seal_shard_a')?.done)return ['Break the first furnace','Follow the eastern passage into Rat Run. Destroy its nest and recover the first seal.'];if(!this.furnaceOpen)return ['Find the brass key','Explore the northern Key Vault, then unlock the gate east of Rat Run.'];if(this.shards<3)return ['Recover the lost seals','Search Bone Barracks to the south and Cinder Gallery to the northeast.'];if(!this.gateOpen)return ['Unseal the Warden’s crypt','Enter Seal Approach and open the three-shard gate.'];if(!this.bossDead)return ['Silence the Bellows Warden','Avoid orange attack marks. Strike between attacks and watch your Ember.'];return ['Leave the Ashvault','The eastern portal is awake. Approach and press E to escape.'];}
 xpThreshold(){return [0,120,360,720,1200,Infinity][this.level];}
 xpFloor(){return [0,0,120,360,720,1200][this.level];}
 gainXp(amount:number){if(this.level>=5)return;this.xp+=amount;let levels=0;while(this.level<5&&this.xp>=this.xpThreshold()){this.level++;this.maxHp+=15;this.hp=Math.min(this.maxHp,this.hp+35);this.bladeDamage+=2;this.burstDamage+=3;levels++;}if(levels){this.particles(this.x,this.y,0x8ff5d9,55);const ring=this.add.circle(this.x,this.y,16,0x7ce3c5,.08).setStrokeStyle(3,0xc8fff0,.95).setDepth(9999);this.tweens.add({targets:ring,radius:95,alpha:0,duration:800,onComplete:()=>ring.destroy()});sound(760,.55,'sine',.045);this.toast(`LEVEL ${this.level} · +15 maximum health · blade empowered`);}}
 updateHud(){const set=(id:string,v:string)=>{const el=document.getElementById(id);if(el)el.textContent=v;};set('health-value',`${Math.ceil(this.hp)} / ${this.maxHp}`);set('ember-value',`${Math.ceil(this.ember)} / 100`);for(const [id,v]of [['health-bar',this.hp/this.maxHp*100],['ember-bar',this.ember]] as const){const el=document.getElementById(id);if(el)el.style.width=v+'%';}set('score',String(this.score).padStart(6,'0'));set('level-value',`WARDEN · LEVEL ${this.level}`);const next=this.xpThreshold(),floor=this.xpFloor();set('xp-value',this.level>=5?'MAX LEVEL':`${this.xp} / ${next} XP`);const xpBar=document.getElementById('xp-bar');if(xpBar)xpBar.style.width=(this.level>=5?100:(this.xp-floor)/(next-floor)*100)+'%';set('key','⚿ '+this.keys);const s=document.getElementById('shards');if(s)s.innerHTML=[0,1,2].map(i=>`<i class="diamond ${i<this.shards?'on':''}"></i>`).join('');set('nest-count',`${this.nests} / 3 FURNACES SILENCED`);set('zone',ZONES[this.zone]||'Forgotten Passage');if(this.d.source==='generated'){set('explored','SEED '+this.d.seed);}set('time',this.timeString());const [title,copy]=this.objective();set('objective-title',title);set('objective-copy',copy);set('explored',this.d.source==='generated'?`SEED ${this.d.seed} · ${this.exploredPercent()}%`:`EXPLORED ${this.exploredPercent()}%`);document.querySelector('#dash-slot')?.classList.toggle('cooldown',this.clock<this.dashAt);document.querySelector('#burst-slot')?.classList.toggle('cooldown',this.ember<18||this.clock<this.burstAt);const boss=this.enemies.find(e=>e.family==='bellows_warden'&&!e.dead);document.querySelector('#boss')?.classList.toggle('hidden',!boss||this.zone!==8);if(boss){const bar=document.getElementById('boss-bar');if(bar)bar.style.width=boss.hp/boss.max*100+'%';set('phase',boss.hp>boss.max*.66?'I · TEMPER':boss.hp>boss.max*.32?'II · OVERPRESSURE':'III · RUPTURE');}this.drawMinimap(document.querySelector('#minimap'));}
 timeString(){return `${Math.floor(this.elapsed/60).toString().padStart(2,'0')}:${Math.floor(this.elapsed%60).toString().padStart(2,'0')}`;}
 toast(message:string){const el=document.querySelector('#toast');if(el){el.textContent=message;el.classList.remove('hidden');this.toastUntil=this.clock+3.5;}}
 pause(){this.paused=true;this.keysDown.clear();this.touch=undefined;ui.insertAdjacentHTML('beforeend',`<div class="modal-shade" id="modal"><div class="modal"><div class="eyebrow">THE FLAME CAN WAIT</div><h2>Take a breath.</h2><p>Your descent is paused. Nothing moves and no Ember is consumed.</p><button class="primary" id="resume">RESUME DESCENT <span>→</span></button><button class="secondary" id="options">SETTINGS <span>⚙</span></button><button class="secondary" id="quit">RETURN TO TITLE <span>↗</span></button></div></div>`);document.querySelector('#resume')!.addEventListener('click',()=>this.resume());document.querySelector('#options')!.addEventListener('click',()=>{document.querySelector('#modal')?.remove();this.showSettings(false);});document.querySelector('#quit')!.addEventListener('click',()=>this.showTitle());}
 resume(){this.paused=false;this.mapOpen=false;this.keysDown.clear();this.renderHud();}
 showSettings(fromTitle:boolean){ui.insertAdjacentHTML('beforeend',`<div class="modal-shade" id="modal"><div class="modal"><div class="eyebrow">MAKE THE CRYPT YOURS</div><h2>Settings</h2><label class="setting">Scene brightness<input id="brightness" type="range" min="85" max="140" value="${settings.brightness*100}" aria-label="Scene brightness"></label><label class="setting">Sound effects<input id="sound" type="checkbox" ${settings.sound?'checked':''}></label><label class="setting">Reduced flashes & shake<input id="flash" type="checkbox" ${settings.reducedFlash?'checked':''}></label><p>Floors stay lighter than walls at every brightness level. Brass edges mark solid boundaries. Orange marks danger; teal marks a benefit.</p><button class="primary" id="back">SAVE & RETURN <span>→</span></button></div></div>`);document.querySelector('#brightness')!.addEventListener('input',e=>{settings.brightness=Number((e.target as HTMLInputElement).value)/100;document.querySelector<HTMLCanvasElement>('#game canvas')!.style.filter=`brightness(${settings.brightness})`;});document.querySelector('#back')!.addEventListener('click',()=>{settings.sound=(document.querySelector('#sound') as HTMLInputElement).checked;settings.reducedFlash=(document.querySelector('#flash') as HTMLInputElement).checked;save();fromTitle?this.showTitle():this.resume();});}
 showMap(){this.paused=true;this.mapOpen=true;this.keysDown.clear();ui.insertAdjacentHTML('beforeend','<div class="map-full"><div class="eyebrow">YOUR DESCENT</div><h2>The Ashvault</h2><button class="small-button" id="close-map">CLOSE · M</button><canvas id="large-map" width="1024" height="768"></canvas></div>');this.drawMinimap(document.querySelector('#large-map'),true);document.querySelector('#close-map')!.addEventListener('click',()=>this.resume());}
 exploredPercent(){let revealed=0;for(const tile of this.explored)revealed+=tile;return Math.max(1,Math.round(revealed/this.explored.length*100));}
 revealMap(worldX:number,worldY:number){const cx=Math.floor(worldX/32),cy=Math.floor(worldY/32),radius=4;for(let y=cy-radius;y<=cy+radius;y++)for(let x=cx-radius;x<=cx+radius;x++){if(x<0||y<0||x>=this.d.width||y>=this.d.height||Math.hypot(x-cx,y-cy)>radius)continue;const i=y*this.d.width+x;if(this.d.collision[i])continue;if(this.sight(worldX,worldY,x*32+16,y*32+16))this.explored[i]=1;}}
 drawMinimap(canvas:HTMLCanvasElement|null,large=false){if(!canvas)return;const c=canvas.getContext('2d')!,sx=canvas.width/this.d.width,sy=canvas.height/this.d.height;c.fillStyle='#071115';c.fillRect(0,0,canvas.width,canvas.height);for(let y=0;y<this.d.height;y++)for(let x=0;x<this.d.width;x++){const i=y*this.d.width+x;if(!this.explored[i]||this.d.collision[i])continue;c.fillStyle='#78908a';c.fillRect(x*sx,y*sy,sx+.1,sy+.1);}for(const o of this.objects){if(o.done)continue;const i=Math.floor(o.y/32)*this.d.width+Math.floor(o.x/32);if(!this.explored[i])continue;if(o.type==='pickup'&&o.properties.item==='seal_shard')c.fillStyle='#83f8d4';else if(o.type==='spawner')c.fillStyle='#f5a052';else if(o.type==='exit')c.fillStyle='#c1b480';else continue;c.fillRect(o.x/32*sx-2,o.y/32*sy-2,4,4);}c.fillStyle='#e8ffec';c.beginPath();c.arc(this.x/32*sx,this.y/32*sy,large?6:3,0,Math.PI*2);c.fill();if(large){c.font='16px Georgia';c.textAlign='center';for(let z=1;z<=8;z++){if(!this.visited.has(z))continue;const cells=this.d.zones.map((v,i)=>v===z&&this.explored[i]?i:-1).filter(i=>i>=0);if(!cells.length)continue;const x=cells.reduce((s,i)=>s+i%this.d.width,0)/cells.length*sx,y=cells.reduce((s,i)=>s+Math.floor(i/this.d.width),0)/cells.length*sy;c.fillStyle='#0b1719df';c.fillRect(x-83,y-15,166,25);c.fillStyle='#e6d9b8';c.fillText(ZONES[z],x,y+3);}}}
 zoneAt(x:number,y:number){return this.d.zones[Math.floor(y/32)*this.d.width+Math.floor(x/32)]||0;}
 solid(x:number,y:number){if(x<0||y<0||x>=this.d.width*32||y>=this.d.height*32)return true;const i=Math.floor(y/32)*this.d.width+Math.floor(x/32);if(this.d.collision[i])return true;const z=this.d.zones[i];if(!this.furnaceOpen&&(this.d.source==='authored'?x>=928:z>=4))return true;if(z===8&&!this.gateOpen)return true;for(const o of this.objects){if(o.type==='door'&&!o.done&&Math.abs(o.x-x)<19&&Math.abs(o.y-y)<43)return true;}return false;}
 canMove(x:number,y:number,r=9){return ![[x-r,y-r],[x+r,y-r],[x-r,y+r],[x+r,y+r]].some(([a,b])=>this.solid(a,b));}
 moveBody(body:{x:number;y:number},dx:number,dy:number,r=9){if(this.canMove(body.x+dx,body.y,r))body.x+=dx;if(this.canMove(body.x,body.y+dy,r))body.y+=dy;}
 sight(ax:number,ay:number,bx:number,by:number){return lineOfSight(this.d,ax,ay,bx,by,(x,y)=>this.solid(x,y));}
 spawn(family:string,x:number,y:number,home?:DungeonObject){if(this.enemies.filter(e=>!e.dead).length>=24)return;const s=stats[family];const e:Entity={id:this.id++,family,x,y,hp:s.hp,max:s.hp,next:this.clock+1.2,born:this.clock+1,hit:0,sprite:this.add.image(x,y,family+'_idle').setDisplaySize(s.size,s.size).setOrigin(.5,.74),shadow:this.add.ellipse(x,y+6,s.size*.5,s.size*.2,0x031015,.45),home};this.enemies.push(e);if(!['ember_nest','bellows_warden'].includes(family))this.particles(x,y,0xe4a257,8);return e;}
 particles(x:number,y:number,color:number,count=12){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,v=20+Math.random()*90;this.sparks.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.35+Math.random()*.4,max:.75,color,size:1+Math.random()*2});}if(this.sparks.length>450)this.sparks.splice(0,this.sparks.length-450);}
 damageEnemy(e:Entity,amount:number){if(e.dead)return;e.hp-=amount;e.hit=this.clock+.14;this.particles(e.x,e.y-12,e.family==='ember_nest'?0xffa348:0xd2ba85,7);const label=this.add.text(e.x,e.y-40,String(amount),{fontFamily:'Georgia',fontSize:'14px',color:'#f7e4aa',stroke:'#172225',strokeThickness:3}).setOrigin(.5).setDepth(11000);this.tweens.add({targets:label,y:label.y-24,alpha:0,duration:650,onComplete:()=>label.destroy()});if(e.family!=='ember_nest'&&e.family!=='bellows_warden'){const a=Math.atan2(e.y-this.y,e.x-this.x);this.moveBody(e,Math.cos(a)*9,Math.sin(a)*9);}if(e.hp<=0){e.dead=true;e.sprite.setTexture(e.family+'_defeat').setAlpha(.65);e.shadow.setAlpha(.15);this.score+=stats[e.family].score;this.particles(e.x,e.y,0xf2b159,22);sound(100,.2,'triangle');if(e.family==='ember_nest'){this.nests++;if(e.home)(e.home as Obj).done=true;this.ember=Math.min(100,this.ember+30);this.toast('Furnace silenced · +30 Ember');if(this.nests===3){this.score+=1000;this.toast('All furnaces silenced · +1,000');}}else if(e.family==='bellows_warden'){this.bossDead=true;this.shots=[];this.ember=Math.min(100,this.ember+50);this.toast('The Bellows Warden falls. The portal awakens.');sound(540,.8,'sine');}else if(e.id%3===0){this.ember=Math.min(100,this.ember+3);}this.gainXp(xpRewards[e.family]||0);this.tweens.add({targets:e.sprite,alpha:.22,duration:2000});}}
 hit(amount:number){if(this.clock<this.invuln||this.clock<this.dashUntil)return;this.hp=Math.max(0,this.hp-amount*(this.clock<this.guard?.5:1));this.invuln=this.clock+.42;this.particles(this.x,this.y,0xe78b67,10);sound(75,.18,'sawtooth',.025);if(!settings.reducedFlash)this.cameras.main.shake(100,.002);if(this.hp<=0)this.die();}
 dash(){if(this.clock<this.dashAt||this.paused||!this.active)return;this.dashAt=this.clock+1.8;this.dashUntil=this.clock+.18;this.particles(this.x,this.y,0x81d9c3,15);sound(450,.15,'sine');}
 burst(){if(this.ember<18||this.clock<this.burstAt||this.paused||!this.active)return;this.ember-=18;this.burstAt=this.clock+.65;this.attackAnim=this.clock+.3;this.hero.setTexture('hero_cast_ember');for(const e of this.enemies)if(!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<155&&this.sight(this.x,this.y,e.x,e.y))this.damageEnemy(e,this.burstDamage);for(const o of this.objects)if(o.type==='secret'&&!o.done&&Math.hypot(o.x-this.x,o.y-this.y)<155)this.openSecret(o);this.particles(this.x,this.y,0xffbc58,70);sound(95,.45,'sawtooth',.035);const ring=this.add.circle(this.x,this.y,12,0xffbd61,.1).setStrokeStyle(3,0xffd38a,.9).setDepth(9999);this.tweens.add({targets:ring,radius:155,alpha:0,duration:450,onComplete:()=>ring.destroy()});if(!settings.reducedFlash)this.cameras.main.shake(140,.003);}
 attack(){if(this.clock<this.attackAt)return;const targets=this.enemies.filter(e=>!e.dead&&Math.hypot(e.x-this.x,e.y-this.y)<(e.family==='bellows_warden'?87:70)&&Math.abs(Phaser.Math.Angle.Wrap(Math.atan2(e.y-this.y,e.x-this.x)-this.face))<1.25&&this.sight(this.x,this.y,e.x,e.y)).sort((a,b)=>Math.hypot(a.x-this.x,a.y-this.y)-Math.hypot(b.x-this.x,b.y-this.y));const secret=this.objects.find(o=>o.type==='secret'&&!o.done&&Math.hypot(o.x-this.x,o.y-this.y)<65);if(!targets.length&&!secret)return;this.attackAt=this.clock+.52;this.attackAnim=this.clock+.22;for(const e of targets.slice(0,3))this.damageEnemy(e,this.bladeDamage);if(secret){secret.next=(secret.next||0)+1;if(secret.next>=2)this.openSecret(secret);}sound(420,.085,'triangle',.025);const arc=this.add.graphics().setDepth(9999);arc.lineStyle(3,0xffe3a0,.95);arc.beginPath();arc.arc(this.x,this.y,53,this.face-.9,this.face+.9);arc.strokePath();this.tweens.add({targets:arc,alpha:0,duration:170,onComplete:()=>arc.destroy()});}
 openSecret(o:Obj){o.done=true;o.sprite?.setAlpha(.2);this.secrets++;this.score+=500;this.toast('A forgotten cache revealed');}
 nearObject(){return this.objects.filter(o=>!o.done&&['door','lever','chest','checkpoint','exit'].includes(o.type)&&Math.hypot(o.x-this.x,o.y-this.y)<85).sort((a,b)=>Math.hypot(a.x-this.x,a.y-this.y)-Math.hypot(b.x-this.x,b.y-this.y))[0];}
 interact(){if(this.paused||!this.active)return;const o=this.nearObject();if(!o)return;if(o.type==='door'){if(o.name==='gate_furnace'){if(!this.keys){this.toast('A brass key is needed · search the northern vault');return;}this.keys--;this.furnaceOpen=true;}if(o.name==='seal_gate'){if(this.shards<3){this.toast('Three seal shards are needed');return;}this.gateOpen=true;}o.done=true;o.sprite?.setTexture('door_open_arch').setAlpha(.5);sound(80,.5,'triangle');this.toast(o.name==='seal_gate'?'The final seal breaks. The Warden awaits.':'The way is open');}else if(o.type==='checkpoint'){o.done=true;this.checkpoint={x:o.x,y:o.y};this.hp=Math.min(this.maxHp,this.hp+35);this.ember=Math.min(100,this.ember+35);this.toast('Ward flame bound · checkpoint activated');this.particles(o.x,o.y,0x88eacb,25);}else if(o.type==='lever'){o.done=true;o.sprite?.setTexture('lever_on');const b=this.objects.find(x=>x.name==='bridge_01');if(b)b.done=true;this.toast('Gallery mechanism activated · the third seal is free');}else if(o.type==='chest'){if(!this.objects.find(x=>x.type==='secret')?.done){this.toast('Break the cracked stone beside the cache');return;}o.done=true;o.sprite?.setTexture('chest_open');this.score+=750;this.hp=Math.min(this.maxHp,this.hp+45);this.toast('Forgotten riches · +750 score · health restored');}else if(o.type==='exit'){if(!this.bossDead){this.toast('The portal is bound to the Bellows Warden');return;}this.win();}sound(620,.25,'sine');}
 pick(o:Obj){const item=o.properties.item;if(item==='seal_shard'){if(o.name==='seal_shard_a'&&!this.objects.find(x=>x.name==='nest_rat_run')?.done)return;if(o.name==='seal_shard_c'&&!this.objects.find(x=>x.name==='lever_gallery')?.done)return;this.shards++;this.score+=500;this.ember=Math.min(100,this.ember+20);this.toast(`Seal recovered · ${this.shards} of 3`);}else if(item==='brass_key'){this.keys++;this.toast('Brass key found · return to the eastern gate');}else if(item.startsWith('health')){if(this.hp>=this.maxHp)return;this.hp=Math.min(this.maxHp,this.hp+(item.includes('large')?45:20));this.toast('Vitality restored');}else if(item==='shield_charm'){this.guard=this.clock+4;this.toast('Guard charm · damage reduced for 4 seconds');}else if(['teal_mana_shard','ember_charge'].includes(item)){if(this.ember>=100)return;this.ember=Math.min(100,this.ember+30);}else this.score+=item==='score_relic'?300:50;o.done=true;o.sprite?.setVisible(false);this.particles(o.x,o.y,0x8bedd5,18);sound(880,.22,'sine');}
 die(){this.active=false;this.deaths++;this.hero.setTexture('hero_defeat');ui.insertAdjacentHTML('beforeend',`<div class="modal-shade"><div class="modal"><div class="eyebrow">THE FLAME FALTERS</div><h2>Rise from the ash.</h2><p>Your seals and destroyed furnaces are preserved when you return to your checkpoint.</p><button class="primary" id="retry">RETRY FROM CHECKPOINT <span>→</span></button><button class="secondary" id="restart">RESTART THE DESCENT <span>↺</span></button></div></div>`);document.querySelector('#retry')!.addEventListener('click',()=>{this.x=this.checkpoint.x;this.y=this.checkpoint.y;this.hp=this.maxHp;this.ember=100;this.score=Math.max(0,this.score-500);this.shots=[];for(const e of this.enemies)if(!['ember_nest','bellows_warden'].includes(e.family)){e.dead=true;e.sprite.setVisible(false);e.shadow.setVisible(false);}for(const o of this.objects)if(o.type==='enemy_group')o.done=false;const boss=this.enemies.find(e=>e.family==='bellows_warden'&&!e.dead);if(boss){boss.hp=boss.max;boss.tell=undefined;boss.x=boss.home!.x;boss.y=boss.home!.y;}this.invuln=this.clock+2;this.active=true;this.paused=false;this.keysDown.clear();this.cameras.main.centerOn(this.x,this.y);this.renderHud();this.toast('Rekindled · permanent progress preserved');});document.querySelector('#restart')!.addEventListener('click',()=>this.start(this.d.source==='generated',this.d.seed));}
 win(){this.active=false;const bonus=(this.deaths===0?2000:0)+Math.max(0,Math.floor(840-this.elapsed)*5);this.score+=bonus;best=Math.max(best,this.score);completed=true;save();sound(780,1,'sine');ui.insertAdjacentHTML('beforeend',`<div class="modal-shade"><div class="modal"><div class="eyebrow">THE ASHVAULT IS SILENT</div><h2>You kept the flame.</h2><p>The Warden is fallen. For the first time in centuries, the furnaces are cold.</p><div class="result-grid"><div>FINAL SCORE<strong>${this.score.toLocaleString()}</strong></div><div>RANK<strong>${this.score>=10000?'S':this.score>=7000?'A':'B'}</strong></div><div>DESCENT TIME<strong>${this.timeString()}</strong></div><div>WARDEN LEVEL<strong>${this.level}</strong></div><div>FURNACES / DEATHS<strong>${this.nests} / ${this.deaths}</strong></div></div><p>Secrets found: ${this.secrets} · Completion bonuses: ${bonus.toLocaleString()}<br>Personal best: ${best.toLocaleString()}</p><button class="primary" id="again">DESCEND AGAIN <span>→</span></button><button class="secondary" id="next-floor">ENTER EXPEDITION <span>→</span></button><button class="secondary" id="home">RETURN TO TITLE <span>↗</span></button></div></div>`);document.querySelector('#again')!.addEventListener('click',()=>this.start(this.d.source==='generated',this.d.seed));document.querySelector('#home')!.addEventListener('click',()=>this.showTitle());document.querySelector('#next-floor')!.addEventListener('click',()=>this.showExpedition());}
 update(_time:number,delta:number){const dt=Math.min(delta/1000,.05);this.titleTime+=dt;if(this.menu){this.cameras.main.centerOn(1080+Math.sin(this.titleTime*.09)*70,780+Math.cos(this.titleTime*.08)*70);this.drawEffects(dt,false);return;}if(!this.active||this.paused)return;this.step+=dt;while(this.step>=1/60){this.simulate(1/60);this.step-=1/60;if(!this.active)break;}this.drawEffects(dt,true);const cam=this.cameras.main;const tx=this.x+Math.cos(this.face)*25,ty=this.y+Math.sin(this.face)*18;cam.centerOn(Phaser.Math.Linear(cam.midPoint.x,tx,.09),Phaser.Math.Linear(cam.midPoint.y,ty,.09));if(this.clock-this.lastHud>.1){this.updateHud();this.lastHud=this.clock;}if(this.clock>this.toastUntil)document.querySelector('#toast')?.classList.add('hidden');}
 updateFlow(){const w=this.d.width,h=this.d.height;this.flow=new Int16Array(w*h).fill(-1);const start=Math.floor(this.y/32)*w+Math.floor(this.x/32);this.flow[start]=0;const q=[start];for(let p=0;p<q.length;p++){const i=q[p],x=i%w,y=Math.floor(i/w);for(const [nx,ny] of [[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){const ni=ny*w+nx;if(nx>=0&&ny>=0&&nx<w&&ny<h&&this.flow[ni]<0&&!this.solid(nx*32+16,ny*32+16)){this.flow[ni]=this.flow[i]+1;q.push(ni);}}}}
 steer(e:Entity){if(this.sight(e.x,e.y,this.x,this.y))return Math.atan2(this.y-e.y,this.x-e.x);const w=this.d.width,x=Math.floor(e.x/32),y=Math.floor(e.y/32),i=y*w+x;let best=this.flow[i],tx=this.x,ty=this.y;for(const [nx,ny]of [[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){const v=this.flow[ny*w+nx];if(v>=0&&(best<0||v<best)){best=v;tx=nx*32+16;ty=ny*32+16;}}return Math.atan2(ty-e.y,tx-e.x);}
 simulate(dt:number){this.clock+=dt;this.elapsed+=dt;if(this.clock>this.mapRevealAt){this.revealMap(this.x,this.y);this.mapRevealAt=this.clock+.12;}if(this.clock>this.flowAt){this.updateFlow();this.flowAt=this.clock+.25;}this.ember=Math.max(0,this.ember-dt*.22);if(this.ember===0){this.hp=Math.max(0,this.hp-dt*1.5);if(this.hp<=0){this.die();return;}}let mx=Number(this.keysDown.has('KeyD')||this.keysDown.has('ArrowRight'))-Number(this.keysDown.has('KeyA')||this.keysDown.has('ArrowLeft')),my=Number(this.keysDown.has('KeyS')||this.keysDown.has('ArrowDown'))-Number(this.keysDown.has('KeyW')||this.keysDown.has('ArrowUp'));if(this.touch&&Math.hypot(this.touch.dx,this.touch.dy)>12){mx=this.touch.dx;my=this.touch.dy;}const pad=navigator.getGamepads?.()[0];if(pad){if(Math.hypot(pad.axes[0],pad.axes[1])>.2){mx=pad.axes[0];my=pad.axes[1];}if(pad.buttons[0]?.pressed)this.burst();if(pad.buttons[1]?.pressed)this.dash();if(pad.buttons[2]?.pressed)this.interact();}
  const length=Math.hypot(mx,my);this.move=length>0;if(length){mx/=length;my/=length;if(!this.mouseAim)this.face=Math.atan2(my,mx);}if(this.mouseAim){const p=this.cameras.main.getWorldPoint(this.pointer.x,this.pointer.y);if(Math.hypot(p.x-this.x,p.y-this.y)>15)this.face=Math.atan2(p.y-this.y,p.x-this.x);}if(this.clock<this.dashUntil)this.moveBody(this,Math.cos(this.face)*315*dt,Math.sin(this.face)*315*dt);else this.moveBody(this,mx*128*dt,my*128*dt);
  this.hero.setPosition(this.x,this.y).setDepth(this.y+1).setFlipX(Math.cos(this.face)<-.1);this.shadow.setPosition(this.x,this.y+7).setDepth(this.y-.5);let texture='hero_idle_breathe_0'+(Math.floor(this.clock*3)%4+1);if(this.clock<this.dashUntil)texture='hero_dash';else if(this.clock<this.attackAnim)texture='hero_attack_0'+(Math.floor(this.clock*16)%4+1);else if(this.move)texture='hero_walk_alt_0'+(Math.floor(this.clock*9)%4+1);this.hero.setTexture(texture).setAlpha(this.clock<this.invuln?.65:1);const z=this.zoneAt(this.x,this.y);if(z&&z!==this.zone){this.zone=z;this.visited.add(z);this.toast(ZONES[z]);}this.attack();
  for(const o of this.objects){if(o.type==='pickup'&&!o.done&&Math.hypot(o.x-this.x,o.y-this.y)<27)this.pick(o);if(o.type==='enemy_group'&&!o.done&&Math.hypot(o.x-this.x,o.y-this.y)<o.properties.activationRadius&&this.sight(this.x,this.y,o.x,o.y)){o.done=true;for(let i=0;i<o.properties.count;i++){const sx=o.x+(i%2)*23,sy=o.y+Math.floor(i/2)*23;if(this.canMove(sx,sy))this.spawn(o.properties.family,sx,sy);}}if(o.type==='pickup'&&!o.done)o.sprite?.setY(o.y+Math.sin(this.clock*2+o.x)*3);if(o.type==='exit'){o.sprite?.setTexture('portal_'+(Math.floor(this.clock*8)%8+1)).setAlpha(this.bossDead?1:.2);}}
  for(const e of this.enemies){if(e.dead)continue;const dist=Math.hypot(e.x-this.x,e.y-this.y),s=stats[e.family];if(dist>460||this.zoneAt(e.x,e.y)!==this.zone&&dist>160)continue;if(e.family==='bellows_warden'&&(!this.gateOpen||this.zone!==8))continue;
   if(e.family==='ember_nest'){if(dist<360&&this.clock>e.next){e.next=this.clock+Number(e.home?.properties.cadence||5);const live=this.enemies.filter(v=>!v.dead&&v.home===e.home&&v.family!=='ember_nest').length;if(live<Number(e.home?.properties.cap||4)){const a=this.clock*2,sx=e.x+Math.cos(a)*35,sy=e.y+Math.sin(a)*35;if(this.canMove(sx,sy))this.spawn(e.home!.properties.family,sx,sy,e.home);}}}
   else if(this.clock>e.born){if(e.tell){if(this.clock>=e.tell.until){const tell=e.tell;e.tell=undefined;if(e.family==='cinder_acolyte'){const a=Math.atan2(tell.y-e.y,tell.x-e.x);this.shots.push({x:e.x,y:e.y,vx:Math.cos(a)*155,vy:Math.sin(a)*155,life:4,damage:10});}else if(e.family==='bellows_warden'){if(Math.hypot(this.x-tell.x,this.y-tell.y)<tell.radius)this.hit(19);this.particles(tell.x,tell.y,0xff9f43,35);if(e.hp<e.max*.66){for(let n=0;n<(e.hp<e.max*.32?12:8);n++){const a=n*Math.PI*2/(e.hp<e.max*.32?12:8)+this.clock;this.shots.push({x:e.x,y:e.y,vx:Math.cos(a)*105,vy:Math.sin(a)*105,life:3,damage:10});}}}else if(Math.hypot(this.x-tell.x,this.y-tell.y)<tell.radius&&this.sight(e.x,e.y,this.x,this.y))this.hit(s.damage);e.next=this.clock+(e.family==='ash_rat'?1:1.6);}}
    else{const ranged=e.family==='cinder_acolyte',boss=e.family==='bellows_warden',range=boss?290:ranged?245:e.family==='furnace_brute'?70:39;if(dist<range&&this.clock>e.next&&this.sight(e.x,e.y,this.x,this.y)){e.tell={until:this.clock+(boss?.95:ranged?.7:e.family==='furnace_brute'?.7:.42),x:boss?this.x:ranged?this.x:e.x+(this.x-e.x)*.6,y:boss?this.y:ranged?this.y:e.y+(this.y-e.y)*.6,radius:boss?(e.hp<e.max*.32?94:72):e.family==='furnace_brute'?64:34};}else if(dist>(ranged?160:29)){const a=this.steer(e),speed=s.speed*(ranged&&dist<180?-1:1);this.moveBody(e,Math.cos(a)*speed*dt,Math.sin(a)*speed*dt,8);}}
   }
   e.sprite.setPosition(e.x,e.y).setDepth(e.y).setFlipX(this.x<e.x).setTexture(e.family+'_'+(e.hit>this.clock?'hit':e.tell?'attack':e.family==='ember_nest'?'idle':Math.floor(this.clock*5)%2?'move_01':'move_02')).setAlpha(this.clock<e.born?.45:1);e.shadow.setPosition(e.x,e.y+6).setDepth(e.y-1);
  }
  for(const p of this.shots){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(this.solid(p.x,p.y))p.life=0;if(Math.hypot(p.x-this.x,p.y-this.y)<15){this.hit(p.damage);p.life=0;}}this.shots=this.shots.filter(p=>p.life>0);const o=this.nearObject(),hint=document.querySelector('#interact');if(hint){hint.classList.toggle('hidden',!o);if(o)hint.textContent='[ E ] '+(o.type==='door'?'Open '+(o.name==='seal_gate'?'seal gate':o.name==='gate_furnace'?'brass gate':'gate'):o.type==='checkpoint'?'Bind checkpoint flame':o.type==='lever'?'Pull the gallery lever':o.type==='exit'?'Enter the portal':'Open the cache');}
 }
 drawEffects(dt:number,play:boolean){this.fx.clear();this.light.clear();const t=this.titleTime;this.world.setTint(0xffffff);const cam=this.cameras.main,v=cam.worldView;
  // Warm light is additive: no dark veil covers navigation or combat.
  for(const o of this.objects){if(!['spawner','checkpoint','exit'].includes(o.type)||o.done&&o.type==='spawner')continue;const color=o.type==='spawner'?0xf18c3a:0x58cdb7;for(let r=3;r>=1;r--){this.light.fillStyle(color,(o.type==='spawner'?.025:.035)*(1+Math.sin(t*3+o.x)*.18));this.light.fillCircle(o.x,o.y,24*r);}if(Math.random()<.15&&!this.paused)this.sparks.push({x:o.x+(Math.random()-.5)*30,y:o.y-10,vx:(Math.random()-.5)*12,vy:-20-Math.random()*15,life:1,max:1,color,size:1});}
  for(const e of this.enemies){if(e.dead)continue;if(e.hp<e.max&&play){const w=e.family==='bellows_warden'?65:34;this.fx.fillStyle(0x08171c,.9);this.fx.fillRect(e.x-w/2,e.y-stats[e.family].size*.75,w,4);this.fx.fillStyle(e.family==='ember_nest'?0xf4b562:0xdb9471,1);this.fx.fillRect(e.x-w/2,e.y-stats[e.family].size*.75,w*e.hp/e.max,4);}if(e.tell){this.fx.fillStyle(0xf28831,settings.reducedFlash?.14:.23);this.fx.fillCircle(e.tell.x,e.tell.y,e.tell.radius);this.fx.lineStyle(2,0xffc16b,.95);this.fx.strokeCircle(e.tell.x,e.tell.y,e.tell.radius);this.fx.lineStyle(1,0xffdfac,.5);this.fx.lineBetween(e.tell.x-8,e.tell.y,e.tell.x+8,e.tell.y);this.fx.lineBetween(e.tell.x,e.tell.y-8,e.tell.x,e.tell.y+8);}}

  // Every locked crossing has a visible grille; never use an invisible gate.
  for(let yy=1;yy<this.d.height-1;yy++)for(let xx=1;xx<this.d.width-1;xx++){const i=yy*this.d.width+xx;if(this.d.collision[i])continue;const x=xx*32,y=yy*32;const locked=(a:number,b:number)=>!this.furnaceOpen&&(this.d.source==='authored'?a>=928:this.zoneAt(a,b)>=4)||!this.gateOpen&&this.zoneAt(a,b)===8;if(!locked(x+16,y+16))continue;this.fx.lineStyle(2,!this.furnaceOpen?0xd9b26d:0x75dcca,.9);for(const [dx,dy]of [[-1,0],[1,0],[0,-1],[0,1]]){if(this.d.collision[(yy+dy)*this.d.width+xx+dx]||locked(x+16+dx*32,y+16+dy*32))continue;const ax=x+(dx===1?32:0),ay=y+(dy===1?32:0);this.fx.lineBetween(ax,ay,ax+(dx?0:32),ay+(dy?0:32));for(let n=4;n<32;n+=7)this.fx.lineBetween(ax+(dx? -4:n),ay+(dy?-4:n),ax+(dx?4:n),ay+(dy?4:n));}}
  for(const p of this.shots){this.light.fillStyle(0xff8034,.16);this.light.fillCircle(p.x,p.y,13);this.fx.fillStyle(0xffd08a,1);this.fx.fillCircle(p.x,p.y,4);}
  for(const p of this.sparks){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;this.fx.fillStyle(p.color,Math.max(0,p.life/p.max));this.fx.fillCircle(p.x,p.y,p.size);}this.sparks=this.sparks.filter(p=>p.life>0);
  if(play){this.fx.lineStyle(1.2,0xb8efda,.65);this.fx.strokeEllipse(this.x,this.y+6,31,16);this.fx.fillStyle(0xe8d69b,.85);const a=this.face;this.fx.fillTriangle(this.x+Math.cos(a)*26,this.y+Math.sin(a)*26,this.x+Math.cos(a+.13)*21,this.y+Math.sin(a+.13)*21,this.x+Math.cos(a-.13)*21,this.y+Math.sin(a-.13)*21);if(this.guard>this.clock){this.fx.lineStyle(2,0x9beddf,.6);this.fx.strokeCircle(this.x,this.y,25);}}
  for(let n=0;n<35;n++){const x=v.x+((n*137.3+t*(n%2?3:-2))%Math.max(1,v.width)+v.width)%v.width,y=v.y+((n*73.9-t*7)%Math.max(1,v.height)+v.height)%v.height;this.fx.fillStyle(n%5===0?0xe5b57c:0xc1d0bd,.16+Math.sin(t+n)*.1);this.fx.fillCircle(x,y,n%3===0?1.2:.6);}
 }
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#101b22',antialias:true,powerPreference:'high-performance',scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},scene:[GameScene],render:{roundPixels:true},audio:{noAudio:true}});
document.addEventListener('DOMContentLoaded',()=>{const canvas=document.querySelector<HTMLCanvasElement>('#game canvas');if(canvas)canvas.style.filter=`brightness(${settings.brightness})`;});
// Local development inspection for reproducible gameplay verification.
if(import.meta.env.DEV)Object.defineProperty(window,'cryptward',{get:()=>scene});

if(import.meta.env.DEV && new URLSearchParams(location.search).has('verify')){ import('./verify').then(({installVerification})=>{const wait=setInterval(()=>{if(scene?.hero){clearInterval(wait);installVerification(scene);}},100);}); }
